### ISSUE TITLE
Kurven in Virtuellen Layern

### ISSUE THREAD

**Issue by ackmar** [opengisch/QGIS-Issues-SH#67]
Virtueller Layer unterstützt keine Curvegeometrietypen. 
Gibt es einen Befehl, wie für PostGIS, welcher Kurven in Linien segmentiert?
Es ist wünschenswert, dass QGIS in zukünftiger Version auch Curves unterstützt.

**Comment by m-kuhn** [comment]
> Virtueller Layer unterstützt keine Curvegeometrietypen.

CC @olivierdalang 

>  Gibt es einen Befehl, wie für PostGIS, welcher Kurven in Linien segmentiert?

Aus https://postgis.net/docs/ST_CurveToLine.html :

```sql
SELECT ST_AsText(ST_CurveToLine(ST_GeomFromText('CIRCULARSTRING(220268 150415,220227 150505,220227 150406)')));
```

**Comment by ackmar** [comment]
Die Funktion 'ST_CurveToLine' wird per importierter Layerdefinition (.GPKG) nicht unterstützt.

![image](https://user-images.githubusercontent.com/34340243/89165583-0a5f5380-d579-11ea-9187-08afbf5f79a1.png)

**Comment by m-kuhn** [comment]
sorry, ich hab mich verlesen und verstanden in postgis. Ich habe leider kein Äquivalent gefunden für virtuelle Layer.

**Comment by olivierdalang** [comment]
AFAIK, spatialite (which underlies virtual layers) doesn't support curved geometries, so it's about updating QgsVLayer sqlite module so that it converts geometry to linear geometries before loading them.

I don't think it can work otherwise (e.g. even `centroid(geometry)` yields null on curved geometries, so we can't linearize afterwards).

I'm not very familiar with this part of the code, but from a quick look in the code, it should be doable.

**Comment by olivierdalang** [comment]
@ackmar 

Our fix has been integrated in QGIS master. Are you able to test using a recent QGIS nightly build to ensure it works with your workflow ?

I'll close this issue in the meantime, feel free to reopen if there's any followup issue.
